### ISSUE TITLE
FL zip + district is weird

### ISSUE THREAD

**Issue by nickoneill** [5calls/civilservices-api#2]
This zip 34956 (east FL) returns the incorrect house district (east FL) even though they're quite a ways apart.

Both geojsons are correct, needs investigation into why it's pointing to the wrong thing.

**Comment by piebob** [comment]
34957 also has this problem

**Comment by nickoneill** [comment]
Fixed this in eb1b89bce978b823fa9e488e421ce12bad8b8030
